jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

#mongodb
data:
  mongodb.host: localhost
  mongodb.port: 27017
  mongodb.uri: mongodb://localhost/account
  mongo.repositories.enabled: true

logging:
  level:
    org.springframework:
      security: INFO